boa.init                 package:boa                 R Documentation

_S_t_a_r_t _S_e_s_s_i_o_n

_D_e_s_c_r_i_p_t_i_o_n:

     boa.init() is the first function called to start a BOA session
     when using the command-line. It sets up the internal data
     structures and initializes them with the appropriate default
     values.

_U_s_a_g_e:

     boa.init(recover = FALSE)

_A_r_g_u_m_e_n_t_s:

 recover: a logical value for use if the previous BOA menu session
          terminated unexpectedly.  It may be possible to crash the
          menu system by supplying the wrong type of data.  In the
          event of a crash, 'recover = TRUE' may be used to ensure that
          no data is lost.

_A_u_t_h_o_r(_s):

     Brian J. Smith

_S_e_e _A_l_s_o:

     'boa.load', 'boa.quit'

